theme: osuny
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params: 
  plausible: ecoconception.mmibordeaux.com
  image_sizes:
    sections:
      posts:
        item:
          desktop:  1600
  debug:
     productionUrl: "https://ecoconception.mmibordeaux.com"
